#!/bin/bash
DB_REPL_USER="repl"
DB_REPL_PASSWORD="Qq123456"
MYSQL_COMMANDS="STOP REPLICA;
CHANGE REPLICATION SOURCE TO SOURCE_HOST='192.168.0.51', SOURCE_USER='$DB_REPL_USER', SOURCE_PASSWORD='$DB_REPL_PASSWORD', SOURCE_AUTO_POSITION = 1, GET_SOURCE_PUBLIC_KEY = 1;
START REPLICA;"
mysql -e "$MYSQL_COMMANDS"
