network:
  ethernets:
    enp0s3:
      dhcp4: no
      addresses: [192.168.0.51/24]
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: default
          via: 192.168.0.1
  version: 2
